variables:
  description: Get the contributor stats summary from all repositories of any given organization
  homepage: https://github.com/caarlos0/org-stats

includes:
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/build.yml
  - from_url:
      url: 'https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/package_with_completions_and_manpages.yml?b=4&cache=0'
  - from_url:
      url: https://raw.githubusercontent.com/caarlos0/goreleaserfiles/main/release.yml

furies:
  - account: caarlos0

snapcrafts:
  - publish: true
    summary: 'GitHub Organization Stats'
    description: 'Get the contributor stats summary from all repositories of any given organization'
    grade: stable
    license: MIT
    apps:
      org-stats:
        plugs: ["home", "network"]


