name: lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          # Use supplied Go version
          skip-go-installation: true
          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=0
          # Optional: working directory, useful for monorepos
          # working-directory: somedir
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
