name: lint

on:
  push:
  pull_request:

jobs:
  golangci:
    name: lint
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ~1.18

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Use supplied Go version
          skip-go-installation: true
          # Optional: golangci-lint command line arguments.
          args: --issues-exit-code=0
          # Optional: working directory, useful for monorepos
          # working-directory: somedir
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
